### ISSUE TITLE
Getting not found error

### ISSUE THREAD

**Issue by pratibha-bhandari** [damirkusar/AngularPhpEmailExample#1]
I am running this sample on my system but I am getting "assets/email.php 404 (Not Found)" whenever I am trying to send an email. Is there any additional steps that I am missing?

**Comment by david95thinkcode** [comment]
Getting the same issue in one project that I'm coding. 
**Where should we put the .php file ?**

**Comment by mariehelene** [comment]
Same error... have you got a solution ??

**Comment by hectorares** [comment]
solve it with
./assets/email.php
generate dist and upload it to a server

**Comment by damirkusar** [comment]
@hectorares will solve the problem. Maybe check with your hoster if everything is enabled for you. 
Will close this issue.. 

thanks @hectorares
